name: student_learning_app
description: A Flutter app for student learning with quizzes and points system.

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0 # For SQLite database operations
  path: ^1.8.3 # For path manipulation (used with sqflite)
  google_sign_in: ^6.1.0
  share_plus: ^7.0.0
  lottie: ^2.7.0 # For Lottie animations
  confetti: ^0.7.0 # For celebration effects
  file_picker: ^10.1.9
  excel: ^2.0.7
  http: ^1.1.0
  html: ^0.15.4
<<<<<<< Updated upstream
  flutter_bloc: ^8.1.4 # For state management
  dio: ^5.4.1 # For HTTP requests
=======
  shared_preferences: ^2.2.2
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # For linting and code analysis

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/images/planet.png
    - assets/images/astronaut.png
    - assets/images/google_icon.png
    - assets/images/beach.jpg
    - assets/images/bird.png
    - assets/images/eduquest_logo.png

#  fonts:
#    - family: YourCustomFont # Optional: Add custom fonts if needed
#      fonts:
#        - asset: assets/fonts/YourCustomFont-Regular.ttf
